version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./cardimg:/mnt/data/cardimg
      - ./opt/mtg:/opt/mtg:ro
      - ./setup/mtgc.conf:/etc/apache2/sites-available/mtgc.conf:ro
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mtg
      MYSQL_USER: mtg
      MYSQL_PASSWORD: mtgpass
    volumes:
      - db-data:/var/lib/mysql
      - ./setup/mtg_new.sql:/docker-entrypoint-initdb.d/mtg_new.sql:ro
      - ./setup/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
volumes:
  db-data:
