version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./cardimg:/mnt/data/cardimg
      - ./opt/mtg:/opt/mtg:ro
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mtg
      MYSQL_USER: mtg
      MYSQL_PASSWORD: mtgpass
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
