# Set __BASE_DIR__ to the log directory (e.g. /var/log/mtg inside the container)
__BASE_DIR__/*.log {
    su www-data www-data
    daily
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
